@url = http://localhost:3000

###
GET {{url}}/autores/

###
GET {{url}}/autores/6

###
POST {{url}}/autores
Content-Type: application/json

{
    "nome":"Coelho Neto",
    "nacionalidade":"Brasil"
}

###
PUT {{url}}/autores/6
Content-Type: application/json

{
    "nome":"Clarice Lispector",
    "nacionalidade":"Ucrâniana"
}

