@url = http://localhost:3000/usuarios


###
GET {{url}}

###
GET {{url}}/1

###
POST {{url}}
Content-Type: application/json

{
    "pessoa_id":"1"
}

###
GET {{url}}/pessoa/11

###
GET {{url}}/emprestimos/2
###


